### ISSUE TITLE
how to find Pretrained Diffusion Models config.json file

### ISSUE THREAD

**Issue by jianan-kristine** [EnVision-Research/LucidDreamer#14]
Firstly, you may need to change model_key: in the configs\<config_file>.yaml to link the local Pretrained Diffusion Models ( [Stable Diffusion 2.1-base](https://github.com/Stability-AI/StableDiffusion) in default)

I wonder how to find config.json file. After downloading the file to "/home/xxx/LucidDreamer-main/stabilityai/stable-diffusion-2-1-base" ,I came across this error.
![image](https://github.com/EnVision-Research/LucidDreamer/assets/81866939/0c18bfaf-354e-4f72-8e45-d8e60ea35b4c)

This is the files in the StableDiffusion model.
![image](https://github.com/EnVision-Research/LucidDreamer/assets/81866939/95465eb1-62cd-4457-8fb9-864dd2d7d94b)

**Comment by YixunLiang** [comment]
Since our model is built on the diffusers, you need to download the whole file in huggingface and then link them. You can do it as follow:
```shell
# HTTPS
git lfs install
git clone https://huggingface.co/stabilityai/stable-diffusion-2-1-base
```
Then, link it. Would not directly clone the repo of [Stable Diffusion 2.1-base](https://github.com/Stability-AI/StableDiffusion) . 

Or you can use the model_key that in <config_file>.yaml.  like ``model_key: 'stabilityai/stable-diffusion-2-1-base`` . Your computer will download it automatically.
