### ISSUE TITLE
How can I generate zero-shot avatar??

### ISSUE THREAD

**Issue by sunwonlikeyou** [EnVision-Research/LucidDreamer#30]
I can't find training codes for Zero-shot avatar..
This code is only for head. Do you have plans about updating about zero-shot avatar generation?

**Comment by AbnerVictor** [comment]
> I can't find training codes for Zero-shot avatar.. This code is only for head. Do you have plans about updating about zero-shot avatar generation?

Thank you for asking.

The zero-shot avatar generation pipeline is under our development and we do not release our code due to the complexity of the new pipeline. Specifically, we add an extra module to render the control signal (depth map of human body, via SMPL) and control the stable diffusion with a depth-control-net, the result is reasonably well.

We may consider adding the pipeline to this repo, but not our top priority.
