### ISSUE TITLE
An  inconsistent error occurred when I used the sample to generate an instance

### ISSUE THREAD

**Issue by xzr52** [EnVision-Research/LucidDreamer#4]
python train.py --opt ./configs/white_hair_ironman.yaml
I didn't modify anything, but an inconsistent error occurred. And I trained for two hours on a 4090。
I want to know why this happens。
 I would be very grateful if you could answer me.
![image](https://github.com/EnVision-Research/LucidDreamer/assets/56352290/b9c8f611-f5e5-47e1-a531-327f3a286c95)

https://github.com/EnVision-Research/LucidDreamer/assets/56352290/61927170-64f7-4e5e-9b32-71a941ed5e96

**Comment by AbnerVictor** [comment]
Hi, thank you for trying our codes and sharing your problem with us. Can you post your environment here? It shouldn't take this long to train on a 4090. We can reproduce our result within 1hr on a 3090. May be you can help us debugging the issue.

And, which error do you mean, I cannot locate it in your screenshots, do you mean the unsatisfying geometry?

BTW, updating your pytorch version to the latest one is sometimes helpful.

**Comment by xzr52** [comment]
I think the problem is that the generated object has three-dimensional inconsistency. It looks like there are faces in front and behind.Thank you for your information. I will reconfigure the environment according to your requirements and retest.

**Comment by YixunLiang** [comment]
Hi, do you have the same problem in JOKER training or just the IRONMAN? we didn't meet such a situation in reproducing. You can try to scale up the phi_range from [-80,80] to [-180,180] and enlarge the rand_cam_gamma，rand_cam_gamma can make the randomly sampled camera more focused on the front face. Or you can try to just replace a noise seed?

**Comment by YixunLiang** [comment]
Here is the video,

https://github.com/EnVision-Research/LucidDreamer/assets/99460842/4293c1c6-51dc-46df-80d7-4e1b67281fe5

**Comment by xzr52** [comment]
Ok thank you very much, I will retrain according to your configuration requirements

**Comment by Volleria** [comment]
Hi, I am currently trying to run this project but  meeting a few issues, If possible，could you provide some contact information(email,qq) for further communication? I hope this won't disturb you

**Comment by YixunLiang** [comment]
Hi, feel free to drop an email to me about your issues.  my email: ***@***.***



---- Replied Message ----
| From | Zhao ***@***.***> |
| Date | 11/28/2023 15:23 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [EnVision-Research/LucidDreamer] An inconsistent error occurred when I used the sample to generate an instance (Issue #4) |

Hi, I am currently trying to run this project but meeting a few issues, If possible，could you provide some contact information(email,qq) for further communication? I hope this won't disturb you

**Comment by Volleria** [comment]
> Hi, feel free to email me about your issues. my email: lyxun2000@gmail.com

Thanks！

**Comment by xzr52** [comment]
I used the environment in environment.yml to install, but the objects I generated seemed wrong again. I wanted to ask what happened, because I used a fixed random seed and it didn't change. I would be very grateful if you could answer my question

https://github.com/EnVision-Research/LucidDreamer/assets/56352290/5f64b42e-b8c7-4154-a8b6-8fd8926851c6

https://github.com/EnVision-Research/LucidDreamer/assets/56352290/723cb3be-63a3-45c0-9d08-97f4f91294d1

**Comment by YixunLiang** [comment]
could you package the config file and the training process images and send them to my email？ because we did not meet such a situation in reproducing， maybe we need you to provide more information to us to help us for debugging. thanks！



---- Replied Message ----
| From | Zeren ***@***.***> |
| Date | 11/28/2023 20:17 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [EnVision-Research/LucidDreamer] An inconsistent error occurred when I used the sample to generate an instance (Issue #4) |

I used the environment in environment.yml to install, but the objects I generated seemed wrong again. I wanted to ask what happened, because I used a fixed random seed and it didn't change. I would be very grateful if you could answer my question

https://github.com/EnVision-Research/LucidDreamer/assets/56352290/5f64b42e-b8c7-4154-a8b6-8fd8926851c6

https://github.com/EnVision-Research/LucidDreamer/assets/56352290/723cb3be-63a3-45c0-9d08-97f4f91294d1

**Comment by xzr52** [comment]
OK I will send it right away

**Comment by Tzy010822** [comment]
I meet the same situation too

**Comment by AbnerVictor** [comment]
> I meet the same situation too

Sometimes simply change the random seed in the config could help, we are still working on reproducing the problem, it is kind of tricky.
